### ISSUE TITLE
Set up a CI server

### ISSUE THREAD

**Issue by HaaLeo** [emilast/vscode-logfile-highlighter#40]
Set up a continuous integration (CI) server like [Travis-CI](https://travis-ci.org/) or [AppVeyor](https://www.appveyor.com/) to
* compile the extension automatically
* run unit tests automatically
* run integration tests automatically  

like it is suggested in the vscode docs:
* [docs for Travis-CI](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines)
* [docs for AppVeyor](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-on-windows-with-appveyor)

**Comment by emilast** [comment]
Agreed, that would be nice. Do you have experience in any of these?

**Comment by HaaLeo** [comment]
I set up Travis-CI before but for a C# project, not typescript. They both support nodejs and npm ([travis-docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/), [AppVeyor-docs](https://www.appveyor.com/docs/lang/nodejs-iojs/)). I think the main difference is more windows specific. But for our purpose both should be fine.

**Comment by emilast** [comment]
Ok. Would be nice to do that but there's no rush I suppose. I'll have a look when I get some time, but that doesn't happen all that often...

**Comment by emilast** [comment]
First simple Travis CI build is not set up at https://travis-ci.org/emilast/vscode-logfile-highlighter.

Also added a build status banner in the readme file. Would be nice to force it to show the status of of the correct branch but I'm not sure of how to do that. I'll leave it for now. If you have more suggestions, feel free to open this issue again :-)

**Comment by HaaLeo** [comment]
Cool. In addition to that it maybe also would be nice to run the `integrationtest` and the `tslint` script , too.

**Comment by emilast** [comment]
Hi. I've added tslint now but the integration tests are not working correctly. They haven't worked on my machine earlier and I have not bothered taking it up with you but maybe we can fix it now.

This is what happens on my machine:

```
PS C:\code\private\vscode-logfile-highlighter> npm run integrationtest

> LogFileHighlighter@2.1.1 integrationtest C:\code\private\vscode-logfile-highlighter
> npm run compile && node ./node_modules/vscode/bin/test


> LogFileHighlighter@2.1.1 compile C:\code\private\vscode-logfile-highlighter
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: C:\code\private\vscode-logfile-highlighter
Downloading VS Code into "C:\code\private\vscode-logfile-highlighter\.vscode-test" from: https://vscode-update.azurewebsites.net/1.20.1/win32-archive/stable
Running extension tests: C:\code\private\vscode-logfile-highlighter\.vscode-test\Code C:\code\private\vscode-logfile-highlighter\out\test --extensionDevelopmentPath=C:\code\private\vscode-logfile-highlighter --extensionTestsPath=C:\code\private\vscode-logfile-highlighter\out\test


[main 4:22:26 PM] update#ctor - updates are disabled

Activating extension `AureliaEffect.aurelia` failed: Cannot find module 'vscode-languageclient'.

Activating extension `AureliaEffect.aurelia` failed:  Cannot find module 'vscode-languageclient'
Here is the error stack:  Error: Cannot find module 'vscode-languageclient'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Function.o._load (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\emil_\.vscode\extensions\AureliaEffect.aurelia-1.0.1\dist\src\client\main.js:5:33)
        at Object.<anonymous> (C:\Users\emil_\.vscode\extensions\AureliaEffect.aurelia-1.0.1\dist\src\client\main.js:57:3)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
No editors associated with document: c:\Users\emil_\.vscode\extensions\eamodio.gitlens-8.0.2\welcome.html
Error: Error: Cannot find module 'C:\code\private\vscode-logfile-highlighter\out\test'
        at t.handleExtensionTests (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:710:691)
       at c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:707:130
        at Object.g [as _notify] (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
        at Object.enter (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
        at n.Class.derive._oncancel._run (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
        at n.Class.derive._oncancel._completed (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
        at c (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:888)
        at q.then.o.(anonymous function) (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:78)
        at Object.g [as _notify] (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
        at Object.enter (c:\code\private\vscode-logfile-highlighter\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)

Tests exited with code: 1

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\emil_\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "integrationtest"
npm ERR! node v7.7.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! LogFileHighlighter@2.1.1 integrationtest: `npm run compile && node ./node_modules/vscode/bin/test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the LogFileHighlighter@2.1.1 integrationtest script 'npm run compile && node ./node_modules/vscode/bin/test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the LogFileHighlighter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && node ./node_modules/vscode/bin/test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs LogFileHighlighter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls LogFileHighlighter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\emil_\AppData\Roaming\npm-cache\_logs\2018-02-25T15_22_40_942Z-debug.log
PS C:\code\private\vscode-logfile-highlighter> npm run integrationtest
```

In Travis, the error is different, perhaps because it's run under Linux:

```
20.56s$ npm run integrationtest
> LogFileHighlighter@2.1.1 integrationtest /home/travis/build/emilast/vscode-logfile-highlighter
> npm run compile && node ./node_modules/vscode/bin/test
> LogFileHighlighter@2.1.1 compile /home/travis/build/emilast/vscode-logfile-highlighter
> tsc -p ./
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/emilast/vscode-logfile-highlighter
Downloading VS Code into "/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test" from: https://vscode-update.azurewebsites.net/1.20.1/linux-x64/stable
Running extension tests: /home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/code /home/travis/build/emilast/vscode-logfile-highlighter/out/test --extensionDevelopmentPath=/home/travis/build/emilast/vscode-logfile-highlighter --extensionTestsPath=/home/travis/build/emilast/vscode-logfile-highlighter/out/test
Xlib:  extension "RANDR" missing on display ":99.0".
Xlib:  extension "RANDR" missing on display ":99.0".
[main 3:25:53 PM] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/home/travis/.nvm/versions/node/v9.6.1"
Run `unset npm_config_prefix` to unset it.
Error: Error: Cannot find module '/home/travis/build/emilast/vscode-logfile-highlighter/out/test'
	at t.handleExtensionTests (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:710:691)
	at /home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:707:130
	at Object.g [as _notify] (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:68:868)
	at Object.enter (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:153)
	at n.Class.derive._creator._run (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:970)
	at n.Class.derive._creator._completed (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:411)
	at n.Class.define.cancel.then (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:75:398)
	at Object.enter (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:71:238)
	at n.Class.derive._creator._run (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:970)
	at n.Class.derive._creator._setCompleteValue (/home/travis/build/emilast/vscode-logfile-highlighter/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:664)
```

Any ideas about what might be wrong?

/Emil

**Comment by HaaLeo** [comment]
I got the integration tests to run [here](https://travis-ci.org/HaaLeo/vscode-logfile-highlighter/jobs/348356666). The key was to add the environment variable [CODE_TESTS_PATH](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines) to specify where the integration tests are.  
Travis shows that everything is OK but actually the integration tests are failing. So this still needs to be fixed.
