### ISSUE TITLE
I cant get highlights from my java app

### ISSUE THREAD

**Issue by digitalplumber** [emilast/vscode-logfile-highlighter#74]
Hi all :)

The plugin works for syslog messages but I can't get it to work for my java app using logback appender below is sample log it won't highlight anything before I customize it, just wanted to know if I was missing anything since the description suggests that it would recognize log level patterns/dates and things like that out of the box. 

2019-06-03 14:00:00,135 ERROR [Timer-Driven Process Thread-141] o.a.nifi.processors.standard.GetSFTP GetSFTP[id=835935fb-5e85-1003-a464-e966fac5812b] Unable to retrieve file /abc.csv due to java.io.FileNotFoundException: Could not find file /abc.csv on remote SFTP Server: {}
java.io.FileNotFoundException: Could not find file /abc.csv on remote SFTP Server
        at org.apache.nifi.processors.standard.util.SFTPTransfer.getInputStream(SFTPTransfer.java:304)
        at org.apache.nifi.processors.standard.util.SFTPTransfer.getInputStream(SFTPTransfer.java:293)
        at org.apache.nifi.processors.standard.GetFileTransfer.onTrigger(GetFileTransfer.java:192)
        at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1122)
        at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:147)
        at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:47)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:128)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-03 14:00:00,256 ERROR [Timer-Driven Process Thread-256] o.a.nifi.processors.standard.GetSFTP GetSFTP[id=49c33aa8-a0a4-1e1c-9a6e-5bb784b1b77f] Unable to retrieve file /abc.csv due to java.io.FileNotFoundException: Could not find file /abc.csv on remote SFTP Server: {}
java.io.FileNotFoundException: Could not find file /abc.csv on remote SFTP Server
        at org.apache.nifi.processors.standard.util.SFTPTransfer.getInputStream(SFTPTransfer.java:304)
        at org.apache.nifi.processors.standard.util.SFTPTransfer.getInputStream(SFTPTransfer.java:293)
        at org.apache.nifi.processors.standard.GetFileTransfer.onTrigger(GetFileTransfer.java:192)

**Comment by digitalplumber** [comment]
So I have an update it works however it does not work on a big log file, for reference the log file I'm trying to analyze is 76M big if I look at a smaller chunk of that same log file it works ....

**Comment by emilast** [comment]
The log sample is correctly colored when I test it:

![image](https://user-images.githubusercontent.com/2369639/63097592-2e451600-bf71-11e9-9448-55517f44f403.png)

Just make sure that the extension is used for the current file:

![image](https://user-images.githubusercontent.com/2369639/63097644-49b02100-bf71-11e9-8cc9-a0e3f6c1286c.png)

Regarding large files there is a limit in VS Code that is stop highlighting very large files and there's not much I can do about it. There may be a setting in the editor to change the size limit.
