### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by simonmd** [emilast/vscode-logfile-highlighter#91]
- Issue Type: `Bug`
- Extension Name: `LogFileHighlighter`
- Extension Version: `2.7.0`
- OS Version: `Darwin x64 19.2.0`
- VSCode version: `1.42.0-exploration`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "emilast.LogFileHighlighter",
				"_lower": "emilast.logfilehighlighter"
			},
			"activationEvent": "onLanguage:log"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal value for `line`"
		},
		{
			"name": "Error",
			"message": "Illegal value for `line`"
		}
	]
}
```

**Comment by HaaLeo** [comment]
@simonmd can you please add the steps how to reproduce this bug?

**Comment by darkvertex** [comment]
I appear to have this same issue. -- In "Log (Extension Host)" I see this full traceback:

```
[2020-01-06 09:40:52.983] [exthost] [error] Error: Illegal value for `line`
    at h._lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:391:466)
    at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:390:368)
    at TimePeriodController.updateTimePeriod (/Volumes/fpsan1/fps/people/alan/.vscode/extensions/emilast.logfilehighlighter-2.7.0/out/src/TimePeriodController.js:39:32)
    at new TimePeriodController (/Volumes/fpsan1/fps/people/alan/.vscode/extensions/emilast.logfilehighlighter-2.7.0/out/src/TimePeriodController.js:15:14)
    at activate (/Volumes/fpsan1/fps/people/alan/.vscode/extensions/emilast.logfilehighlighter-2.7.0/out/src/extension.js:11:28)
    at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:911)
    at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:562)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:694:651
    at Function.all (<anonymous>:null:null)
```


If it helps: I'm on VSCode (stable, not "insiders") `1.41.1` on Linux x64 `3.10.0-1062.9.1.el7.x86_64` (my distro is `CentOS 7.7`).

**Comment by HaaLeo** [comment]
@darkvertex thx for the logs, I could reproduce the bug and am working on a fix.
